# Generated by Django 4.0 on 2022-01-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='event_id',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_available_for_emergengy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='professional_areas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
