# Generated by Django 4.0 on 2022-01-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='social_case',
        ),
    ]
