# Generated by Django 4.0 on 2022-01-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0004_socialcase_reviews'),
        ('users', '0003_remove_review_social_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='social_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_cases.socialcase'),
        ),
    ]
