# Generated by Django 4.0 on 2022-01-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review_social_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='social_case',
        ),
    ]
