# Generated by Django 4.0 on 2021-12-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_is_volunteer_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_nr',
            field=models.CharField(max_length=20),
        ),
    ]
