# Generated by Django 4.0 on 2021-12-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_phone_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_nr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
