# Generated by Django 4.0 on 2022-01-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0007_review_blog_comment_review_event_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='blog_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog'),
        ),
    ]
