# Generated by Django 4.0 on 2021-12-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
