# Generated by Django 4.0 on 2021-12-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_nr',
            field=models.IntegerField(),
        ),
    ]
