# Generated by Django 4.0 on 2021-12-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_phone_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_nr',
            field=models.CharField(max_length=12),
        ),
    ]
