# Generated by Django 4.0 on 2022-01-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='gps_coordinates',
            field=models.DecimalField(decimal_places=8, default=10.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organisation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
