# Generated by Django 4.0 on 2022-01-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
