# Generated by Django 4.0 on 2022-01-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_organizer_event_gps_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='gps_coordinates',
            new_name='gps_coordinates_lat',
        ),
        migrations.AddField(
            model_name='event',
            name='gps_coordinates_long',
            field=models.DecimalField(decimal_places=8, default=10.0, max_digits=20),
        ),
    ]
