# Generated by Django 4.0 on 2021-12-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_profile'),
        ('social_cases', '0003_remove_socialcase_tags_remove_socialcase_user_and_more'),
        ('events', '0004_event_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='social_case_organizer',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
