# Generated by Django 4.0 on 2022-01-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('newsletter', '0003_alter_newsletter_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
    ]
