# Generated by Django 4.0 on 2022-01-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('newsletter', '0004_newsletter_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_tag',
            field=models.ManyToManyField(to='events.Tag'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_tags',
            field=models.ManyToManyField(to='events.Tag'),
        ),
    ]
