# Generated by Django 4.0 on 2021-12-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0002_socialcase_profile_image_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcase',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='socialcase',
            name='user',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='SocialCase',
        ),
    ]
