# Generated by Django 4.0 on 2021-12-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialcase',
            old_name='user',
            new_name='profile',
        ),
    ]
