# Generated by Django 4.0 on 2022-01-08 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_review_social_case'),
        ('social_cases', '0003_rename_user_socialcase_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcase',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.review'),
        ),
    ]
