# Generated by Django 4.0 on 2022-01-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0003_remove_socialcase_raised_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='social_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_so_far', to='social_cases.socialcase'),
        ),
    ]
