# Generated by Django 4.0 on 2022-01-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0004_socialcase_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcase',
            name='reviews',
        ),
    ]
