# Generated by Django 4.0 on 2022-01-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0006_socialcase_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcase',
            name='review',
        ),
    ]
