# Generated by Django 4.0 on 2022-01-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0007_remove_socialcase_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcase',
            name='donations',
        ),
        migrations.AddField(
            model_name='socialcase',
            name='donation_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
