# Generated by Django 4.0 on 2022-01-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0009_socialcase_donations_alter_donation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcase',
            name='donation_target',
        ),
    ]
