# Generated by Django 4.0 on 2022-01-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0010_remove_socialcase_donation_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='target_donation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
