# Generated by Django 4.0 on 2022-01-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0011_donation_target_donation_alter_donation_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='social_case',
        ),
    ]
