# Generated by Django 4.0 on 2022-01-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0013_remove_socialcase_donations_donation_social_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcase',
            name='donations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_cases.donation'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='social_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_cases.socialcase'),
        ),
    ]
