# Generated by Django 4.0 on 2022-01-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0014_socialcase_donations_alter_donation_social_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcase',
            name='donations',
        ),
    ]
