# Generated by Django 4.0 on 2022-01-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0015_remove_socialcase_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='target_donation',
        ),
        migrations.AddField(
            model_name='socialcase',
            name='target_donation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
