# Generated by Django 4.0 on 2022-01-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0017_rename_amount_donation_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcase',
            name='raised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
