# Generated by Django 4.0 on 2022-01-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0018_socialcase_raised_delete_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcase',
            name='organizer',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
