# Generated by Django 4.0 on 2022-01-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_cases', '0019_socialcase_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcase',
            name='organizer',
        ),
    ]
